# Makefile generated by XPJ for crossbridge
-include Makefile.custom
ProjectName = PhysXCommonFixed
PhysXCommonFixed_cppfiles   += ./../../foundation/src/PsAllocator.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/PsAssert.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/PsErrorHandler.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/PsFastIPC.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/PsFastXml.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/PsFoundation.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/PsMathUtils.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/PsTempAllocator.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/PsUtilities.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixAtomic.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixCpu.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixFPU.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixMemoryMappedFile.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixMutex.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixPAEventSrc.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixPrintString.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixSList.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixSocket.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixSync.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixThread.cpp
PhysXCommonFixed_cppfiles   += ./../../foundation/src/unix/PsUnixTime.cpp
PhysXCommonFixed_cppfiles   += ./../../Common/src/CmCollection.cpp
PhysXCommonFixed_cppfiles   += ./../../Common/src/CmEventProfiler.cpp
PhysXCommonFixed_cppfiles   += ./../../Common/src/CmFreeListAllocator.cpp
PhysXCommonFixed_cppfiles   += ./../../Common/src/CmMathUtils.cpp
PhysXCommonFixed_cppfiles   += ./../../Common/src/CmPtrTable.cpp
PhysXCommonFixed_cppfiles   += ./../../Common/src/CmRenderOutput.cpp
PhysXCommonFixed_cppfiles   += ./../../Common/src/CmVisualization.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuBoxPruning.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuCCTSweepTests.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuCapsule.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuContainer.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuContainerMemoryMgmt.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuContainerMemoryMgmtPS3.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuDebug.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuGeomUtilsInternal.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuGeometryQuery.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuGeometryUnion.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuMTD.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuMeshFactory.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuMetaData.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuObjectBounds.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuOverlapTests.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuRaycastTests.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuRevisitedRadix.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuRevisitedRadixBuffered.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuSerialize.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuSweepMTD.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuSweepSharedTests.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/GuSweepTests.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/contact/GuContactCapsuleMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/contact/GuContactConvexMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/contact/GuContactPolygonPolygon.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/contact/GuContactSphereMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/contact/GuFeatureCode.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/common/GuBarycentricCoordinates.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/common/GuSeparatingAxes.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/convex/GuBigConvexData.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/convex/GuConvexHelper.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/convex/GuConvexMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/convex/GuConvexSupportTable.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/convex/GuConvexUtilsInternal.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/convex/GuCubeIndex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/convex/GuHillClimbing.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/convex/GuShapeConvex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/distance/GuDistancePointBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/distance/GuDistancePointSegment.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/distance/GuDistancePointTriangle.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/distance/GuDistanceSegmentBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/distance/GuDistanceSegmentSegment.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/distance/GuDistanceSegmentTriangle.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepBoxBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepBoxSphere.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepBoxTriangle_FeatureBased.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepBoxTriangle_SAT.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepCapsuleBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepCapsuleCapsule.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepCapsuleTriangle.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepSphereCapsule.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepSphereSphere.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepSphereTriangle.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/sweep/GuSweepTriangleUtils.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/gjk/GuEPA.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/gjk/GuEPAPenetrationWrapper.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/gjk/GuGJKFallBack.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/gjk/GuGJKPenetrationWrapper.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/gjk/GuGJKSimplex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/gjk/GuGJKSimplexTesselation.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/gjk/GuGJKWrapperFixed.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/gjk/GuVecBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/intersection/GuIntersectionBoxBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/intersection/GuIntersectionEdgeEdge.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/intersection/GuIntersectionRayBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/intersection/GuIntersectionRayCapsule.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/intersection/GuIntersectionRaySphere.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/intersection/GuIntersectionRayTriangle.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/intersection/GuIntersectionTriangleBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuHybridModel.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuInternalTriangleMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuMeshInterface.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuMeshQuery.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuMidphase.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuOverlapTestsMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuRTree.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuRTreeQueries.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuSweepsMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/mesh/GuTriangleMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/hf/GuHeightField.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/hf/GuHeightFieldUtil.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/hf/GuOverlapTestsHF.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/hf/GuSweepsHF.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactBoxBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactBoxConvex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactCapsuleBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactCapsuleConvex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactCapsuleHeightField.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactCapsuleMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactConvexCommon.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactConvexConvex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactConvexHeightField.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactConvexMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactGenBoxConvex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactGenSphereCapsule.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactPlaneBox.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactPlaneCapsule.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactPlaneConvex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactSphereConvex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactSphereHeightField.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMContactSphereMesh.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMShapeConvex.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPCMTriangleContactGen.cpp
PhysXCommonFixed_cppfiles   += ./../../GeomUtils/src/pcm/GuPersistentContactManifold.cpp

PhysXCommonFixed_cpp_debug_dep    = $(addprefix $(DEPSDIR)/PhysXCommonFixed/debug/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(PhysXCommonFixed_cppfiles)))))
PhysXCommonFixed_cc_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(PhysXCommonFixed_ccfiles)))))
PhysXCommonFixed_c_debug_dep      = $(addprefix $(DEPSDIR)/PhysXCommonFixed/debug/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(PhysXCommonFixed_cfiles)))))
PhysXCommonFixed_debug_dep      = $(PhysXCommonFixed_cpp_debug_dep) $(PhysXCommonFixed_cc_debug_dep) $(PhysXCommonFixed_c_debug_dep)
-include $(PhysXCommonFixed_debug_dep)
PhysXCommonFixed_cpp_checked_dep    = $(addprefix $(DEPSDIR)/PhysXCommonFixed/checked/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(PhysXCommonFixed_cppfiles)))))
PhysXCommonFixed_cc_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(PhysXCommonFixed_ccfiles)))))
PhysXCommonFixed_c_checked_dep      = $(addprefix $(DEPSDIR)/PhysXCommonFixed/checked/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(PhysXCommonFixed_cfiles)))))
PhysXCommonFixed_checked_dep      = $(PhysXCommonFixed_cpp_checked_dep) $(PhysXCommonFixed_cc_checked_dep) $(PhysXCommonFixed_c_checked_dep)
-include $(PhysXCommonFixed_checked_dep)
PhysXCommonFixed_cpp_profile_dep    = $(addprefix $(DEPSDIR)/PhysXCommonFixed/profile/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(PhysXCommonFixed_cppfiles)))))
PhysXCommonFixed_cc_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(PhysXCommonFixed_ccfiles)))))
PhysXCommonFixed_c_profile_dep      = $(addprefix $(DEPSDIR)/PhysXCommonFixed/profile/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(PhysXCommonFixed_cfiles)))))
PhysXCommonFixed_profile_dep      = $(PhysXCommonFixed_cpp_profile_dep) $(PhysXCommonFixed_cc_profile_dep) $(PhysXCommonFixed_c_profile_dep)
-include $(PhysXCommonFixed_profile_dep)
PhysXCommonFixed_cpp_release_dep    = $(addprefix $(DEPSDIR)/PhysXCommonFixed/release/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(PhysXCommonFixed_cppfiles)))))
PhysXCommonFixed_cc_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(PhysXCommonFixed_ccfiles)))))
PhysXCommonFixed_c_release_dep      = $(addprefix $(DEPSDIR)/PhysXCommonFixed/release/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(PhysXCommonFixed_cfiles)))))
PhysXCommonFixed_release_dep      = $(PhysXCommonFixed_cpp_release_dep) $(PhysXCommonFixed_cc_release_dep) $(PhysXCommonFixed_c_release_dep)
-include $(PhysXCommonFixed_release_dep)
PhysXCommonFixed_debug_hpaths    := 
PhysXCommonFixed_debug_hpaths    += ./../../../Include/foundation
PhysXCommonFixed_debug_hpaths    += ./../../foundation/include
PhysXCommonFixed_debug_hpaths    += ./../../../Include/physxprofilesdk
PhysXCommonFixed_debug_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXCommonFixed_debug_hpaths    += ./../../../Include/common
PhysXCommonFixed_debug_hpaths    += ./../../../Include
PhysXCommonFixed_debug_hpaths    += ./../../Common/src
PhysXCommonFixed_debug_hpaths    += ./../../Common/src/unix
PhysXCommonFixed_debug_hpaths    += ./../../PhysXProfile/include
PhysXCommonFixed_debug_hpaths    += ./../../PhysXProfile/src
PhysXCommonFixed_debug_hpaths    += ./../../../Include/geometry
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/headers
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/contact
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/common
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/convex
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/distance
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/sweep
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/gjk
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/intersection
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/mesh
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/hf
PhysXCommonFixed_debug_hpaths    += ./../../GeomUtils/src/pcm
PhysXCommonFixed_debug_lpaths    := 
PhysXCommonFixed_debug_defines   := $(PhysXCommonFixed_custom_defines)
PhysXCommonFixed_debug_defines   += PX_FOUNDATION_EXPORTS
PhysXCommonFixed_debug_defines   += PX_PHYSX_COMMON_EXPORTS
PhysXCommonFixed_debug_defines   += _DEBUG
PhysXCommonFixed_debug_defines   += PX_DEBUG
PhysXCommonFixed_debug_defines   += PX_CHECKED
PhysXCommonFixed_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
PhysXCommonFixed_debug_libraries := 
PhysXCommonFixed_debug_common_cflags	:= $(PhysXCommonFixed_custom_cflags)
PhysXCommonFixed_debug_common_cflags    += -MMD
PhysXCommonFixed_debug_common_cflags    += $(addprefix -D, $(PhysXCommonFixed_debug_defines))
PhysXCommonFixed_debug_common_cflags    += $(addprefix -I, $(PhysXCommonFixed_debug_hpaths))
PhysXCommonFixed_debug_common_cflags  += 
PhysXCommonFixed_debug_common_cflags  +=   -fPIC    -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
PhysXCommonFixed_debug_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
PhysXCommonFixed_debug_common_cflags  += -Wno-long-long
PhysXCommonFixed_debug_common_cflags  += -Wno-unknown-pragmas -Wno-invalid-offsetof -Wno-uninitialized -Wno-attributes 
PhysXCommonFixed_debug_common_cflags  += -Wno-unused-parameter -Wno-missing-field-initializers 
PhysXCommonFixed_debug_common_cflags  += -g3 -gdwarf-2
PhysXCommonFixed_debug_cflags	:= $(PhysXCommonFixed_debug_common_cflags)
PhysXCommonFixed_debug_cppflags	:= $(PhysXCommonFixed_debug_common_cflags)
PhysXCommonFixed_debug_lflags    := $(PhysXCommonFixed_custom_lflags)
PhysXCommonFixed_debug_lflags    += $(addprefix -L, $(PhysXCommonFixed_debug_lpaths))
PhysXCommonFixed_debug_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXCommonFixed_debug_libraries)) -Wl,--end-group
PhysXCommonFixed_debug_lflags  += 
PhysXCommonFixed_debug_lflags  += 
PhysXCommonFixed_debug_objsdir  = $(OBJS_DIR)/PhysXCommonFixed_debug
PhysXCommonFixed_debug_cpp_o    = $(addprefix $(PhysXCommonFixed_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXCommonFixed_cppfiles)))))
PhysXCommonFixed_debug_cc_o    = $(addprefix $(PhysXCommonFixed_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXCommonFixed_ccfiles)))))
PhysXCommonFixed_debug_c_o      = $(addprefix $(PhysXCommonFixed_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXCommonFixed_cfiles)))))
PhysXCommonFixed_debug_obj      = $(PhysXCommonFixed_debug_cpp_o) $(PhysXCommonFixed_debug_cc_o) $(PhysXCommonFixed_debug_c_o)
PhysXCommonFixed_debug_bin      := ./../../../Lib/crossbridge/libPhysX3CommonDEBUG_x86.a

clean_PhysXCommonFixed_debug: 
	@$(ECHO) clean PhysXCommonFixed debug
	@$(RMDIR) $(PhysXCommonFixed_debug_objsdir)
	@$(RMDIR) $(PhysXCommonFixed_debug_bin)
	@$(RMDIR) $(DEPSDIR)/PhysXCommonFixed/debug

build_PhysXCommonFixed_debug: postbuild_PhysXCommonFixed_debug
postbuild_PhysXCommonFixed_debug: mainbuild_PhysXCommonFixed_debug
mainbuild_PhysXCommonFixed_debug: prebuild_PhysXCommonFixed_debug $(PhysXCommonFixed_debug_bin)
prebuild_PhysXCommonFixed_debug:

$(PhysXCommonFixed_debug_bin): $(PhysXCommonFixed_debug_obj) 
	mkdir -p `dirname ./../../../Lib/crossbridge/libPhysX3CommonDEBUG_x86.a`
	##$(CXX) -shared $(PhysXCommonFixed_debug_obj) $(PhysXCommonFixed_debug_lflags) -lc -o $@ 
	@$(AR) rcs $(PhysXCommonFixed_debug_bin) $(PhysXCommonFixed_debug_obj)
	$(ECHO) building $@ complete!

PhysXCommonFixed_debug_DEPDIR = $(dir $(@))/$(*F)
$(PhysXCommonFixed_debug_cpp_o): $(PhysXCommonFixed_debug_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(PhysXCommonFixed_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/PhysXCommonFixed/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))))
	cp $(PhysXCommonFixed_debug_DEPDIR).d $(addprefix $(DEPSDIR)/PhysXCommonFixed/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/PhysXCommonFixed/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))).P; \
	  rm -f $(PhysXCommonFixed_debug_DEPDIR).d

$(PhysXCommonFixed_debug_cc_o): $(PhysXCommonFixed_debug_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling debug $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(PhysXCommonFixed_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))))
	cp $(PhysXCommonFixed_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))).debug.P; \
	  rm -f $(PhysXCommonFixed_debug_DEPDIR).d

$(PhysXCommonFixed_debug_c_o): $(PhysXCommonFixed_debug_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(PhysXCommonFixed_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/PhysXCommonFixed/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))))
	cp $(PhysXCommonFixed_debug_DEPDIR).d $(addprefix $(DEPSDIR)/PhysXCommonFixed/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/PhysXCommonFixed/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_debug_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))).P; \
	  rm -f $(PhysXCommonFixed_debug_DEPDIR).d

PhysXCommonFixed_checked_hpaths    := 
PhysXCommonFixed_checked_hpaths    += ./../../../Include/foundation
PhysXCommonFixed_checked_hpaths    += ./../../foundation/include
PhysXCommonFixed_checked_hpaths    += ./../../../Include/physxprofilesdk
PhysXCommonFixed_checked_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXCommonFixed_checked_hpaths    += ./../../../Include/common
PhysXCommonFixed_checked_hpaths    += ./../../../Include
PhysXCommonFixed_checked_hpaths    += ./../../Common/src
PhysXCommonFixed_checked_hpaths    += ./../../Common/src/unix
PhysXCommonFixed_checked_hpaths    += ./../../PhysXProfile/include
PhysXCommonFixed_checked_hpaths    += ./../../PhysXProfile/src
PhysXCommonFixed_checked_hpaths    += ./../../../Include/geometry
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/headers
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/contact
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/common
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/convex
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/distance
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/sweep
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/gjk
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/intersection
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/mesh
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/hf
PhysXCommonFixed_checked_hpaths    += ./../../GeomUtils/src/pcm
PhysXCommonFixed_checked_lpaths    := 
PhysXCommonFixed_checked_defines   := $(PhysXCommonFixed_custom_defines)
PhysXCommonFixed_checked_defines   += PX_FOUNDATION_EXPORTS
PhysXCommonFixed_checked_defines   += PX_PHYSX_COMMON_EXPORTS
PhysXCommonFixed_checked_defines   += NDEBUG
PhysXCommonFixed_checked_defines   += PX_CHECKED
PhysXCommonFixed_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
PhysXCommonFixed_checked_libraries := 
PhysXCommonFixed_checked_common_cflags	:= $(PhysXCommonFixed_custom_cflags)
PhysXCommonFixed_checked_common_cflags    += -MMD
PhysXCommonFixed_checked_common_cflags    += $(addprefix -D, $(PhysXCommonFixed_checked_defines))
PhysXCommonFixed_checked_common_cflags    += $(addprefix -I, $(PhysXCommonFixed_checked_hpaths))
PhysXCommonFixed_checked_common_cflags  += 
PhysXCommonFixed_checked_common_cflags  +=   -fPIC    -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
PhysXCommonFixed_checked_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
PhysXCommonFixed_checked_common_cflags  += -Wno-long-long
PhysXCommonFixed_checked_common_cflags  += -Wno-unknown-pragmas -Wno-invalid-offsetof -Wno-uninitialized -Wno-attributes 
PhysXCommonFixed_checked_common_cflags  += -Wno-unused-parameter -Wno-missing-field-initializers 
PhysXCommonFixed_checked_common_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
PhysXCommonFixed_checked_cflags	:= $(PhysXCommonFixed_checked_common_cflags)
PhysXCommonFixed_checked_cppflags	:= $(PhysXCommonFixed_checked_common_cflags)
PhysXCommonFixed_checked_lflags    := $(PhysXCommonFixed_custom_lflags)
PhysXCommonFixed_checked_lflags    += $(addprefix -L, $(PhysXCommonFixed_checked_lpaths))
PhysXCommonFixed_checked_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXCommonFixed_checked_libraries)) -Wl,--end-group
PhysXCommonFixed_checked_lflags  += 
PhysXCommonFixed_checked_lflags  += 
PhysXCommonFixed_checked_objsdir  = $(OBJS_DIR)/PhysXCommonFixed_checked
PhysXCommonFixed_checked_cpp_o    = $(addprefix $(PhysXCommonFixed_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXCommonFixed_cppfiles)))))
PhysXCommonFixed_checked_cc_o    = $(addprefix $(PhysXCommonFixed_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXCommonFixed_ccfiles)))))
PhysXCommonFixed_checked_c_o      = $(addprefix $(PhysXCommonFixed_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXCommonFixed_cfiles)))))
PhysXCommonFixed_checked_obj      = $(PhysXCommonFixed_checked_cpp_o) $(PhysXCommonFixed_checked_cc_o) $(PhysXCommonFixed_checked_c_o)
PhysXCommonFixed_checked_bin      := ./../../../Lib/crossbridge/libPhysX3CommonCHECKED_x86.a

clean_PhysXCommonFixed_checked: 
	@$(ECHO) clean PhysXCommonFixed checked
	@$(RMDIR) $(PhysXCommonFixed_checked_objsdir)
	@$(RMDIR) $(PhysXCommonFixed_checked_bin)
	@$(RMDIR) $(DEPSDIR)/PhysXCommonFixed/checked

build_PhysXCommonFixed_checked: postbuild_PhysXCommonFixed_checked
postbuild_PhysXCommonFixed_checked: mainbuild_PhysXCommonFixed_checked
mainbuild_PhysXCommonFixed_checked: prebuild_PhysXCommonFixed_checked $(PhysXCommonFixed_checked_bin)
prebuild_PhysXCommonFixed_checked:

$(PhysXCommonFixed_checked_bin): $(PhysXCommonFixed_checked_obj) 
	mkdir -p `dirname ./../../../Lib/crossbridge/libPhysX3CommonCHECKED_x86.a`
	##$(CXX) -shared $(PhysXCommonFixed_checked_obj) $(PhysXCommonFixed_checked_lflags) -lc -o $@ 
	@$(AR) rcs $(PhysXCommonFixed_checked_bin) $(PhysXCommonFixed_checked_obj)
	$(ECHO) building $@ complete!

PhysXCommonFixed_checked_DEPDIR = $(dir $(@))/$(*F)
$(PhysXCommonFixed_checked_cpp_o): $(PhysXCommonFixed_checked_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(PhysXCommonFixed_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/PhysXCommonFixed/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))))
	cp $(PhysXCommonFixed_checked_DEPDIR).d $(addprefix $(DEPSDIR)/PhysXCommonFixed/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/PhysXCommonFixed/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))).P; \
	  rm -f $(PhysXCommonFixed_checked_DEPDIR).d

$(PhysXCommonFixed_checked_cc_o): $(PhysXCommonFixed_checked_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling checked $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(PhysXCommonFixed_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))))
	cp $(PhysXCommonFixed_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))).checked.P; \
	  rm -f $(PhysXCommonFixed_checked_DEPDIR).d

$(PhysXCommonFixed_checked_c_o): $(PhysXCommonFixed_checked_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(PhysXCommonFixed_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/PhysXCommonFixed/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))))
	cp $(PhysXCommonFixed_checked_DEPDIR).d $(addprefix $(DEPSDIR)/PhysXCommonFixed/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/PhysXCommonFixed/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_checked_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))).P; \
	  rm -f $(PhysXCommonFixed_checked_DEPDIR).d

PhysXCommonFixed_profile_hpaths    := 
PhysXCommonFixed_profile_hpaths    += ./../../../Include/foundation
PhysXCommonFixed_profile_hpaths    += ./../../foundation/include
PhysXCommonFixed_profile_hpaths    += ./../../../Include/physxprofilesdk
PhysXCommonFixed_profile_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXCommonFixed_profile_hpaths    += ./../../../Include/common
PhysXCommonFixed_profile_hpaths    += ./../../../Include
PhysXCommonFixed_profile_hpaths    += ./../../Common/src
PhysXCommonFixed_profile_hpaths    += ./../../Common/src/unix
PhysXCommonFixed_profile_hpaths    += ./../../PhysXProfile/include
PhysXCommonFixed_profile_hpaths    += ./../../PhysXProfile/src
PhysXCommonFixed_profile_hpaths    += ./../../../Include/geometry
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/headers
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/contact
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/common
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/convex
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/distance
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/sweep
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/gjk
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/intersection
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/mesh
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/hf
PhysXCommonFixed_profile_hpaths    += ./../../GeomUtils/src/pcm
PhysXCommonFixed_profile_lpaths    := 
PhysXCommonFixed_profile_defines   := $(PhysXCommonFixed_custom_defines)
PhysXCommonFixed_profile_defines   += PX_FOUNDATION_EXPORTS
PhysXCommonFixed_profile_defines   += PX_PHYSX_COMMON_EXPORTS
PhysXCommonFixed_profile_defines   += NDEBUG
PhysXCommonFixed_profile_defines   += PX_PROFILE
PhysXCommonFixed_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
PhysXCommonFixed_profile_libraries := 
PhysXCommonFixed_profile_common_cflags	:= $(PhysXCommonFixed_custom_cflags)
PhysXCommonFixed_profile_common_cflags    += -MMD
PhysXCommonFixed_profile_common_cflags    += $(addprefix -D, $(PhysXCommonFixed_profile_defines))
PhysXCommonFixed_profile_common_cflags    += $(addprefix -I, $(PhysXCommonFixed_profile_hpaths))
PhysXCommonFixed_profile_common_cflags  += 
PhysXCommonFixed_profile_common_cflags  +=   -fPIC    -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
PhysXCommonFixed_profile_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
PhysXCommonFixed_profile_common_cflags  += -Wno-long-long
PhysXCommonFixed_profile_common_cflags  += -Wno-unknown-pragmas -Wno-invalid-offsetof -Wno-uninitialized -Wno-attributes 
PhysXCommonFixed_profile_common_cflags  += -Wno-unused-parameter -Wno-missing-field-initializers 
PhysXCommonFixed_profile_common_cflags  += -O3 -fno-strict-aliasing
PhysXCommonFixed_profile_cflags	:= $(PhysXCommonFixed_profile_common_cflags)
PhysXCommonFixed_profile_cppflags	:= $(PhysXCommonFixed_profile_common_cflags)
PhysXCommonFixed_profile_lflags    := $(PhysXCommonFixed_custom_lflags)
PhysXCommonFixed_profile_lflags    += $(addprefix -L, $(PhysXCommonFixed_profile_lpaths))
PhysXCommonFixed_profile_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXCommonFixed_profile_libraries)) -Wl,--end-group
PhysXCommonFixed_profile_lflags  += 
PhysXCommonFixed_profile_lflags  += 
PhysXCommonFixed_profile_objsdir  = $(OBJS_DIR)/PhysXCommonFixed_profile
PhysXCommonFixed_profile_cpp_o    = $(addprefix $(PhysXCommonFixed_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXCommonFixed_cppfiles)))))
PhysXCommonFixed_profile_cc_o    = $(addprefix $(PhysXCommonFixed_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXCommonFixed_ccfiles)))))
PhysXCommonFixed_profile_c_o      = $(addprefix $(PhysXCommonFixed_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXCommonFixed_cfiles)))))
PhysXCommonFixed_profile_obj      = $(PhysXCommonFixed_profile_cpp_o) $(PhysXCommonFixed_profile_cc_o) $(PhysXCommonFixed_profile_c_o)
PhysXCommonFixed_profile_bin      := ./../../../Lib/crossbridge/libPhysX3CommonPROFILE_x86.a

clean_PhysXCommonFixed_profile: 
	@$(ECHO) clean PhysXCommonFixed profile
	@$(RMDIR) $(PhysXCommonFixed_profile_objsdir)
	@$(RMDIR) $(PhysXCommonFixed_profile_bin)
	@$(RMDIR) $(DEPSDIR)/PhysXCommonFixed/profile

build_PhysXCommonFixed_profile: postbuild_PhysXCommonFixed_profile
postbuild_PhysXCommonFixed_profile: mainbuild_PhysXCommonFixed_profile
mainbuild_PhysXCommonFixed_profile: prebuild_PhysXCommonFixed_profile $(PhysXCommonFixed_profile_bin)
prebuild_PhysXCommonFixed_profile:

$(PhysXCommonFixed_profile_bin): $(PhysXCommonFixed_profile_obj) 
	mkdir -p `dirname ./../../../Lib/crossbridge/libPhysX3CommonPROFILE_x86.a`
	##$(CXX) -shared $(PhysXCommonFixed_profile_obj) $(PhysXCommonFixed_profile_lflags) -lc -o $@ 
	@$(AR) rcs $(PhysXCommonFixed_profile_bin) $(PhysXCommonFixed_profile_obj)
	$(ECHO) building $@ complete!

PhysXCommonFixed_profile_DEPDIR = $(dir $(@))/$(*F)
$(PhysXCommonFixed_profile_cpp_o): $(PhysXCommonFixed_profile_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(PhysXCommonFixed_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/PhysXCommonFixed/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))))
	cp $(PhysXCommonFixed_profile_DEPDIR).d $(addprefix $(DEPSDIR)/PhysXCommonFixed/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/PhysXCommonFixed/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))).P; \
	  rm -f $(PhysXCommonFixed_profile_DEPDIR).d

$(PhysXCommonFixed_profile_cc_o): $(PhysXCommonFixed_profile_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling profile $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(PhysXCommonFixed_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))))
	cp $(PhysXCommonFixed_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))).profile.P; \
	  rm -f $(PhysXCommonFixed_profile_DEPDIR).d

$(PhysXCommonFixed_profile_c_o): $(PhysXCommonFixed_profile_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(PhysXCommonFixed_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/PhysXCommonFixed/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))))
	cp $(PhysXCommonFixed_profile_DEPDIR).d $(addprefix $(DEPSDIR)/PhysXCommonFixed/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/PhysXCommonFixed/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_profile_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))).P; \
	  rm -f $(PhysXCommonFixed_profile_DEPDIR).d

PhysXCommonFixed_release_hpaths    := 
PhysXCommonFixed_release_hpaths    += ./../../../Include/foundation
PhysXCommonFixed_release_hpaths    += ./../../foundation/include
PhysXCommonFixed_release_hpaths    += ./../../../Include/physxprofilesdk
PhysXCommonFixed_release_hpaths    += ./../../../Include/physxvisualdebuggersdk
PhysXCommonFixed_release_hpaths    += ./../../../Include/common
PhysXCommonFixed_release_hpaths    += ./../../../Include
PhysXCommonFixed_release_hpaths    += ./../../Common/src
PhysXCommonFixed_release_hpaths    += ./../../Common/src/unix
PhysXCommonFixed_release_hpaths    += ./../../PhysXProfile/include
PhysXCommonFixed_release_hpaths    += ./../../PhysXProfile/src
PhysXCommonFixed_release_hpaths    += ./../../../Include/geometry
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/headers
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/contact
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/common
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/convex
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/distance
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/sweep
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/gjk
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/intersection
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/mesh
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/hf
PhysXCommonFixed_release_hpaths    += ./../../GeomUtils/src/pcm
PhysXCommonFixed_release_lpaths    := 
PhysXCommonFixed_release_defines   := $(PhysXCommonFixed_custom_defines)
PhysXCommonFixed_release_defines   += PX_FOUNDATION_EXPORTS
PhysXCommonFixed_release_defines   += PX_PHYSX_COMMON_EXPORTS
PhysXCommonFixed_release_defines   += NDEBUG
PhysXCommonFixed_release_libraries := 
PhysXCommonFixed_release_common_cflags	:= $(PhysXCommonFixed_custom_cflags)
PhysXCommonFixed_release_common_cflags    += -MMD  
PhysXCommonFixed_release_common_cflags    += $(addprefix -D, $(PhysXCommonFixed_release_defines))
PhysXCommonFixed_release_common_cflags    += $(addprefix -I, $(PhysXCommonFixed_release_hpaths))
PhysXCommonFixed_release_common_cflags  += 
PhysXCommonFixed_release_common_cflags  +=   -fPIC    -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
PhysXCommonFixed_release_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
PhysXCommonFixed_release_common_cflags  += -Wno-long-long
PhysXCommonFixed_release_common_cflags  += -Wno-unknown-pragmas -Wno-invalid-offsetof -Wno-uninitialized -Wno-attributes 
PhysXCommonFixed_release_common_cflags  += -Wno-unused-parameter -Wno-missing-field-initializers 
PhysXCommonFixed_release_common_cflags  += -O3 -fno-strict-aliasing
PhysXCommonFixed_release_cflags	:= $(PhysXCommonFixed_release_common_cflags)
PhysXCommonFixed_release_cppflags	:= $(PhysXCommonFixed_release_common_cflags)
PhysXCommonFixed_release_lflags    := $(PhysXCommonFixed_custom_lflags)
PhysXCommonFixed_release_lflags    += $(addprefix -L, $(PhysXCommonFixed_release_lpaths))
PhysXCommonFixed_release_lflags    += -Wl,--start-group $(addprefix -l, $(PhysXCommonFixed_release_libraries)) -Wl,--end-group
PhysXCommonFixed_release_lflags  += 
PhysXCommonFixed_release_lflags  += 
PhysXCommonFixed_release_objsdir  = $(OBJS_DIR)/PhysXCommonFixed_release
PhysXCommonFixed_release_cpp_o    = $(addprefix $(PhysXCommonFixed_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(PhysXCommonFixed_cppfiles)))))
PhysXCommonFixed_release_cc_o    = $(addprefix $(PhysXCommonFixed_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(PhysXCommonFixed_ccfiles)))))
PhysXCommonFixed_release_c_o      = $(addprefix $(PhysXCommonFixed_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(PhysXCommonFixed_cfiles)))))
PhysXCommonFixed_release_obj      = $(PhysXCommonFixed_release_cpp_o) $(PhysXCommonFixed_release_cc_o) $(PhysXCommonFixed_release_c_o)
PhysXCommonFixed_release_bin      := ./../../../Lib/crossbridge/libPhysX3CommonFixed_x86.a

clean_PhysXCommonFixed_release: 
	@$(ECHO) clean PhysXCommonFixed release
	@$(RMDIR) $(PhysXCommonFixed_release_objsdir)
	@$(RMDIR) $(PhysXCommonFixed_release_bin)
	@$(RMDIR) $(DEPSDIR)/PhysXCommonFixed/release

build_PhysXCommonFixed_release: postbuild_PhysXCommonFixed_release
postbuild_PhysXCommonFixed_release: mainbuild_PhysXCommonFixed_release
mainbuild_PhysXCommonFixed_release: prebuild_PhysXCommonFixed_release $(PhysXCommonFixed_release_bin)
prebuild_PhysXCommonFixed_release: 


$(PhysXCommonFixed_release_bin): $(PhysXCommonFixed_release_obj) 
	mkdir -p `dirname ./../../../Lib/crossbridge/libPhysX3Common_x86.a`
	##$(CXX) -shared -pthread $(PhysXCommonFixed_release_obj) $(PhysXCommonFixed_release_lflags) -O4 -flto-api=$(PhysXCommonFixed_exportfile) -lc -o $@ 
	@$(AR) rcs $(PhysXCommonFixed_release_bin) $(PhysXCommonFixed_release_obj)
	$(ECHO) building $@ complete!

PhysXCommonFixed_release_DEPDIR = $(dir $(@))/$(*F)
$(PhysXCommonFixed_release_cpp_o): $(PhysXCommonFixed_release_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(PhysXCommonFixed_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/PhysXCommonFixed/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))))
	cp $(PhysXCommonFixed_release_DEPDIR).d $(addprefix $(DEPSDIR)/PhysXCommonFixed/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/PhysXCommonFixed/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cppfiles))))).P; \
	  rm -f $(PhysXCommonFixed_release_DEPDIR).d

$(PhysXCommonFixed_release_cc_o): $(PhysXCommonFixed_release_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling release $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(PhysXCommonFixed_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))))
	cp $(PhysXCommonFixed_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_ccfiles))))).release.P; \
	  rm -f $(PhysXCommonFixed_release_DEPDIR).d

$(PhysXCommonFixed_release_c_o): $(PhysXCommonFixed_release_objsdir)/%.o:
	$(ECHO) PhysXCommonFixed: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(PhysXCommonFixed_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/PhysXCommonFixed/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))))
	cp $(PhysXCommonFixed_release_DEPDIR).d $(addprefix $(DEPSDIR)/PhysXCommonFixed/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(PhysXCommonFixed_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/PhysXCommonFixed/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(PhysXCommonFixed_release_objsdir),, $@))), $(PhysXCommonFixed_cfiles))))).P; \
	  rm -f $(PhysXCommonFixed_release_DEPDIR).d

clean_PhysXCommonFixed:  clean_PhysXCommonFixed_debug clean_PhysXCommonFixed_checked clean_PhysXCommonFixed_profile clean_PhysXCommonFixed_release
	rm -rf $(DEPSDIR)

export VERBOSE
ifndef VERBOSE
.SILENT:
endif
